version: "3.3"
services:
  dc-core:
    build: .
    image: "dc-core:latest"
  dc-web:
    build: "web"
    image: "dc-web:latest"
    ports:
      - "${DOCKER_PORT}:80"
    tmpfs:
      - "/usr/temp"
    restart: "unless-stopped"
